version: '3'
services:
  artifactory-telaviv:
    image: docker.bintray.io/jfrog/artifactory-oss:7.12.5
    container_name: artifactory-telviv
    ports:
     - 8081:8082
    volumes:
     - ./data/artifactory:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  jenkins:
          #image: jenkins/jenkins:2.271
    build:
       context: ./Jenkins
       dockerfile:  Dockerfile.jenkins
    container_name: jenkins-master
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ~/jenkins_new1:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

